name: Docker Image CI

on:
  push:
    tags:
    - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Get tag
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # Runs a set of commands using the runners shell
      - name: Build image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/nginx:${{ steps.get_version.outputs.VERSION }}
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:${{ steps.get_version.outputs.VERSION }}
